More fixes for logging in e2e tests.

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -45,36 +45,60 @@ jobs:
 
       - name: Test Super Bias Creation
         run: |
+          set +e
           export START=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
 
           kubectl exec banzai-e2e-test -c banzai-listener -- pytest -s --pyargs banzai --durations=0 --junitxml=/archive/engineering/pytest-master-bias.xml -m master_bias
-      
-          kubectl logs banzai-e2e-test --since-time=$START --all-containers
+          EXIT_CODE=$?
+          
+          # Always print logs even if (especially if?) the reduction fails
+          kubectl logs banzai-e2e-test --since-time=$START --all-containers --prefix=true
+
+          # Exit with the captured status so the job properly fails or succeeds
+          exit $EXIT_CODE
 
       - name: Test Super Dark Creation
         run: |
+          set +e
           export START=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
 
           kubectl exec banzai-e2e-test -c banzai-listener -- pytest -s --pyargs banzai --durations=0 --junitxml=/archive/engineering/pytest-master-dark.xml -m master_dark
-      
-          kubectl logs banzai-e2e-test --since-time=$START --all-containers
+          EXIT_CODE=$?
+          
+          # Always print logs even if (especially if?) the reduction fails
+          kubectl logs banzai-e2e-test --since-time=$START --all-containers --prefix=true
+          
+          # Exit with the captured status so the job properly fails or succeeds
+          exit $EXIT_CODE
 
       - name: Test Super Flat Creation
         run: |
+          set +e
           export START=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
 
           kubectl exec banzai-e2e-test -c banzai-listener -- pytest -s --pyargs banzai --durations=0 --junitxml=/archive/engineering/pytest-master-flat.xml -m master_flat
+          EXIT_CODE=$?
+          
+          # Always print logs even if (especially if?) the reduction fails
+          kubectl logs banzai-e2e-test --since-time=$START --all-containers --prefix=true
 
-          kubectl logs banzai-e2e-test --since-time=$START --all-containers
-      
+          # Exit with the captured status so the job properly fails or succeeds
+          exit $EXIT_CODE
+
       - name: Test Science Frame Creation
         run: |
+          set +e
           export START=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
 
           kubectl exec banzai-e2e-test -c banzai-listener -- pytest -s --pyargs banzai --durations=0 --junitxml=/archive/engineering/pytest-science-files.xml -m science_files
+          EXIT_CODE=$?
 
-          kubectl logs banzai-e2e-test --since-time=$START --all-containers
-      
+          # Always print logs even if (especially if?) the reduction fails
+          kubectl logs banzai-e2e-test --since-time=$START --all-containers --prefix=true
+
+          # Exit with the captured status so the job properly fails or succeeds
+          exit $EXIT_CODE
+
       - name: Cleanup
         run: |
           kubectl delete pod banzai-e2e-test
